name: user_profile_module
description: "New Features User Profile"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  get_it: ^8.0.3
  injectable: ^2.5.0
  freezed_annotation: ^2.4.4
  dartz: ^0.10.1
  connectivity_plus: ^4.0.2
  go_router: ^14.7.2
  module_manager:
    path: ../module_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  injectable_generator: ^2.7.0
  mocktail: ^1.0.4
